export type TDeliveryStatus =
  | 'WAITING_ADDRESS'
  | 'WAITING_PAYMENT'
  | 'ADDRESS_EXPIRED'
  | 'WAITING_ADDRESS'
  | 'READY'
  | 'SHIPPED'
  | 'COMPLETED'
  | 'SHIPPING_EXPIRED'
  | 'CANCELLED';
